module.exports = {
    UPDATE_SCHEMA: 'UPDATE_SCHEMA',
    UPDATE_TABLE_FIELDS: 'UPDATE_TABLE_FIELDS',
    CREATE_FIELD: 'CREATE_FIELD',
    UPDATE_FIELD: 'UPDATE_FIELD',
    DESTROY_FIELD: 'DESTROY_FIELD',

    FIELD_TYPE_VARCHAR: 'varchar',
    FIELD_TYPE_INT: 'int',
    FIELD_TYPE_SERIAL: 'serial'
};
